'use strict';
(() => {
  const data = JSON.parse(document.getElementById('demo-data').textContent);
  const state = { id: 'affiliation-drop', stage: 'bronze', opened: new Set(), live: false, busy: false, results: new Map() };
  const $ = id => document.getElementById(id);
  const escape = value => String(value ?? '').replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]));
  const pretty = value => typeof value === 'string' ? value : JSON.stringify(value, null, 2);
  const code = value => `<pre class="json-code">${escape(JSON.stringify(value, null, 2))}</pre>`;
  const current = () => state.results.get(state.id) || data.scenarios.find(s => s.id === state.id);
  const index = () => data.scenarios.findIndex(s => s.id === state.id);
  const kinds = { 'affiliation-drop': ['A dropped mapping', 'Recover from the source', 'DECISION: REPAIR', ''], 'orcid-conflict': ['An identity conflict', 'Pause for human evidence', 'DECISION: REVIEW', 'review'], 'sparse-metadata': ['A legitimate gap', 'Leave the record alone', 'DECISION: PRESERVE', 'control'], 'doi-replay': ['A repeated delivery', 'Replay without duplicates', 'DECISION: DEDUPLICATE', ''] };
  const labels = { 'observed-fixture-with-injected-fault': 'REAL SOURCE / INJECTED FAULT', 'synthetic': 'FICTIONAL IDENTITY FIXTURE', 'synthetic-negative-control': 'SYNTHETIC NEGATIVE CONTROL', 'observed-fixture-with-synthetic-deliveries': 'REAL SOURCE / SIMULATED RETRY' };
  function toast(message) { $('toast').textContent = message; $('toast').classList.add('visible'); clearTimeout(toast.timer); toast.timer = setTimeout(() => $('toast').classList.remove('visible'), 3500); }
  function download(name, value, type = 'application/json') { const blob = new Blob([typeof value === 'string' ? value : JSON.stringify(value, null, 2)], { type }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 2000); toast(`Downloaded ${name}`); }
  function row(label, value, mono = false) { return `<div class="data-row"><span class="data-label">${escape(label)}</span><div class="data-value${mono ? ' mono' : ''}">${escape(typeof value === 'string' ? value : pretty(value))}</div></div>`; }
  function checks(items) { return `<ul class="check-list">${items.map(c => `<li><span class="check-icon${c.passed ? '' : ' fail'}" aria-label="${c.passed ? 'Passed' : 'Failed'}">${c.passed ? '✓' : '×'}</span><div>${escape(c.name)}<small>${escape(c.detail)}</small></div></li>`).join('')}</ul>`; }
  function renderCases() { $('case-list').innerHTML = data.scenarios.map((s, i) => { const k = kinds[s.id]; return `<button class="case-button${state.id === s.id ? ' selected' : ''}" data-case="${escape(s.id)}" aria-pressed="${state.id === s.id}"><span class="case-num">0${i + 1}</span><span><strong>${k[0]}</strong><small>${k[1]}</small><span class="case-tag ${k[3]}">${k[2]}</span></span></button>`; }).join(''); }
  function targetAuthor(s, record) { return record?.authorships?.[s.id === 'affiliation-drop' ? 2 : 0] || {}; }
  function bronzePanel(s) {
    const a = targetAuthor(s, s.bronze.record);
    const isReal = s.source_kind.startsWith('observed');
    const text = s.id === 'affiliation-drop' ? 'The preserved public snapshot includes Shrey’s Nirma University mapping. A deliberate fault removes it only from the derived copy. The source remains intact.' : s.description;
    return `<div class="panel-heading"><h3>Source receipt</h3><span>${isReal ? 'PINNED PUBLIC SNAPSHOT' : 'LABELLED SYNTHETIC INPUT'}</span></div><p class="panel-copy">${escape(text)}</p>
      ${row('WORK ID', s.source.id.replace('https://openalex.org/', ''), true)}
      ${row('AUTHOR', a.author?.display_name || '—')}
      ${row('RAW AFFILIATION', (a.raw_affiliation_strings || []).join('\n') || 'No raw affiliation supplied')}
      ${s.id === 'orcid-conflict' ? row('RAW ORCID', a.raw_orcid, true) + row('RESOLVED ORCID', a.author?.orcid, true) : row('MAPPED INSTITUTION', (a.affiliations || []).flatMap(x => x.institution_ids || []).map(id => id.replace('https://openalex.org/', '')).join(', ') || '[] · no mapping asserted', true)}
      ${s.id === 'doi-replay' ? row('DELIVERED DOIS', s.findings[0].before, true) : ''}
      <div class="checksum"><strong>SHA-256 · preserved bronze payload</strong><br>${escape(s.bronze.sha256)}</div>
      <details class="evidence-details"><summary>Inspect the preserved record JSON</summary>${code(s.bronze.record)}</details>`;
  }
  function silverPanel(s) {
    const replayed = state.opened.has(s.id);
    const finding = s.findings[0];
    let beforeAfter = '';
    if (finding) {
      beforeAfter = `<table class="change-table"><caption class="panel-copy" style="text-align:left">${replayed ? 'Observed local replay comparison' : 'Recorded comparison from the verified Python run'}</caption><thead><tr><th scope="col">FIELD</th><th scope="col">BEFORE</th><th scope="col">AFTER</th></tr></thead><tbody><tr><td>${escape(finding.path)}</td><td>${escape(pretty(finding.before))}</td><td>${escape(pretty(finding.after))}</td></tr></tbody></table>`;
    } else {
      beforeAfter = `<div class="status-card control"><span class="status-eyebrow">UNCHANGED IS THE RIGHT RESULT</span><h3>Empty mapping. No invented institution.</h3><p>The source does not establish an institutional identity. The normalized view preserves that uncertainty.</p></div>`;
    }
    return `<div class="panel-heading"><h3>Derived record</h3><span>LOCAL MATERIALIZATION</span></div><p class="panel-copy">${escape(s.expected_outcome)}</p>${beforeAfter}
      ${row('DELIVERIES', `${s.metrics.deliveries} supplied payload${s.metrics.deliveries === 1 ? '' : 's'}`)}
      ${row('MATERIALIZATIONS', `${s.metrics.materializations} stable work record`)}
      ${row('LOCAL SCOPE', `${s.metrics.fixture_works} work · ${s.metrics.fixture_authorships} authorship${s.metrics.fixture_authorships === 1 ? '' : 's'} · ${s.metrics.affected_authorships} affected`)}
      <p class="review-note">${s.id === 'affiliation-drop' ? 'The restore uses the exact institution object from this work’s intact snapshot. It does not infer a new institution from a name.' : s.id === 'doi-replay' ? 'Deduplication requires the same work ID and identical normalized content. Distinct work IDs remain distinct even if their DOIs match.' : 'There is no automatic identity correction. Uncertainty remains visible in the record.'}</p>
      <details class="evidence-details"><summary>Inspect the derived input before review</summary>${code(s.silver.before)}</details><details class="evidence-details"><summary>Inspect the final materialization</summary>${code(s.silver.after)}</details>`;
  }
  function goldPanel(s) {
    if (!state.opened.has(s.id)) return `<div class="status-card control"><span class="status-eyebrow">FOLLOW THE EVIDENCE</span><h3>Ready to inspect the decision?</h3><p>Use “${state.live ? 'Run Python replay' : 'Inspect verified replay'}” above to open this case’s outcome and regression checks.</p></div>`;
    const className = s.outcome.status === 'review' ? 'review' : s.outcome.status === 'abstained' ? 'control' : '';
    return `<div class="replay-result"><div class="status-card ${className}"><span class="status-eyebrow">${state.live && state.results.has(s.id) ? 'EXECUTED BY THE LOCAL PYTHON ENGINE' : 'VERIFIED PYTHON OUTPUT · BUNDLED WITH THIS FILE'}</span><h3>${escape(s.outcome.label)}</h3><p>${escape(s.outcome.summary)}</p></div>
      <div class="panel-heading"><h3>The decision</h3><span>${s.metrics.repairs} REPAIR${s.metrics.repairs === 1 ? '' : 'S'} · ${s.metrics.findings} FINDING${s.metrics.findings === 1 ? '' : 'S'}</span></div><p class="panel-copy">${escape(s.outcome.decision)}</p>
      ${s.findings.map(f => `<details class="evidence-details finding-evidence"><summary>${escape(f.code)} · inspect the supporting evidence</summary>${f.evidence.map(e => row(e.label, e.value, true)).join('')}</details>`).join('')}
      <div class="panel-heading"><h3>Regression receipt</h3><span>${s.regression.checks.filter(c => c.passed).length}/${s.regression.checks.length} CHECKS PASS</span></div>${checks(s.regression.checks)}
      <div class="result-actions"><button class="button light" data-action="bundle">Export evidence <span aria-hidden="true">↓</span></button><button class="button light" data-action="test">Export regression test <span aria-hidden="true">↓</span></button><button class="button light" data-action="reply">Save support reply <span aria-hidden="true">↓</span></button></div>
      <div class="support-reply"><p class="eyebrow">CLOSE THE LOOP / ILLUSTRATIVE REPLY</p><p>${escape(s.support_reply)}</p></div></div>`;
  }
  function renderCase() {
    const s = current();
    const opened = state.opened.has(s.id);
    const buttonText = state.busy ? 'Running the Python engine…' : state.live ? (opened ? 'Run Python replay again' : 'Run Python replay') : (opened ? 'Review verified replay' : 'Inspect verified replay');
    $('case-content').innerHTML = `<div class="case-topline"><span class="file-label">CASE 0${index() + 1} / SUPPORT DESK</span><span class="synthetic-label">${labels[s.source_kind]}</span></div><h3 class="ticket-title">${escape(s.ticket.subject)}</h3><p class="ticket-body">“${escape(s.ticket.body)}”</p><div class="ticket-persona">${escape(s.ticket.persona)} · constructed support ticket</div><div class="action-row"><button class="button primary" data-action="replay" ${state.busy ? 'disabled' : ''}>${buttonText} <span aria-hidden="true">↗</span></button><span class="case-hint">${state.live ? 'Runs locally. No OpenAlex API writes.' : 'Recorded Python results. No server needed.'}</span></div>
      <div class="trace-nav" role="tablist" aria-label="Pipeline evidence stages">${[['bronze', '01', 'Source'], ['silver', '02', 'Transform'], ['gold', '03', 'Decision']].map(([id, num, name]) => `<button class="trace-tab${state.stage === id ? ' active' : ''}" id="tab-${id}" role="tab" aria-selected="${state.stage === id}" aria-controls="evidence-panel" tabindex="${state.stage === id ? '0' : '-1'}" data-stage="${id}"><span class="layer-dot ${id}"></span>${num} ${name}</button>`).join('')}</div><div id="evidence-panel" role="tabpanel" aria-labelledby="tab-${state.stage}" tabindex="0">${state.stage === 'bronze' ? bronzePanel(s) : state.stage === 'silver' ? silverPanel(s) : goldPanel(s)}</div>`;
  }
  function renderEvaluation() { const ev = data.evaluation; $('test-passed').textContent = ev.passed; $('test-total').textContent = ev.total; $('evaluation-details').innerHTML = `<p>${escape(ev.scope)} Results were generated by the bundled Python engine.</p>${checks(ev.cases)}<button class="button light" id="download-evaluation" style="margin-top:18px">Download evaluation JSON <span aria-hidden="true">↓</span></button>`; $('download-evaluation').addEventListener('click', () => download('repair-desk-evaluation.json', ev)); }
  function renderSources() { const src = data.meta.sources[0]; $('source-notes').innerHTML = `<p><strong>The boundary:</strong> this local replay harness demonstrates four bounded decisions. It does not run OpenAlex’s production pipeline, train a model, submit curations, or measure accuracy across the corpus. The static HTML replays recorded evidence; the included Python server can execute each case locally.</p><p><strong>The source:</strong> public metadata for <a href="https://openalex.org/W4410234973" target="_blank" rel="noopener">W4410234973</a>, fetched ${escape(src.retrieved_at)}. The article’s full text is not included. SHA-256: <code style="overflow-wrap:anywhere">${escape(src.sha256)}</code>.</p><ul><li><a href="https://help.openalex.org/data/authorships/" target="_blank" rel="noopener">Authorships and the raw-to-resolved affiliation mapping</a></li><li><a href="https://help.openalex.org/data/raw-affiliation-strings/" target="_blank" rel="noopener">Raw affiliation strings and their provenance</a></li><li><a href="https://help.openalex.org/access/fixing-errors/ai-curation-guide/" target="_blank" rel="noopener">OpenAlex’s AI curation guide</a></li><li><a href="https://help.openalex.org/access/fixing-errors/" target="_blank" rel="noopener">The existing correction workflow</a></li></ul><p><strong>Authorship:</strong> created with AI assistance for Shrey Patel’s application. The intended contribution is the choice of problem, explicit decision boundaries, and inspectable evidence. The source pack includes the implementation, evaluation, and engineering note.</p>`; }
  async function runReplay() {
    if (state.busy) return;
    const requestedId = state.id;
    if (state.live) {
      state.busy = true; renderCase();
      try { const response = await fetch('/api/replay', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ scenario: requestedId }), signal: AbortSignal.timeout(15000) }); if (!response.ok) throw new Error('Replay endpoint failed'); const result = await response.json(); if (result.id !== requestedId || !result.regression) throw new Error('Invalid replay response'); state.results.set(requestedId, result); state.opened.add(requestedId); if (state.id === requestedId) state.stage = 'gold'; toast('Python replay completed. The evidence is ready.'); }
      catch { toast('The local engine is unavailable. Bundled evidence is still available.'); state.live = false; updateMode(); }
      finally { state.busy = false; renderCase(); }
    } else { state.opened.add(requestedId); state.stage = 'gold'; renderCase(); }
  }
  function updateMode() { $('mode-pill').classList.toggle('live', state.live); $('mode-pill').innerHTML = `<span></span> ${state.live ? 'Python engine connected · local execution' : 'Bundled evidence · offline ready'}`; }
  function regressionFile(s) { return `"""Exported regression for The Repair Desk. Run from the source-pack root.\nScenario and ticket are synthetic; observed metadata is a pinned public snapshot.\nUsage: python3 -m unittest discover -s tests -p 'test_${s.id.replaceAll('-', '_')}.py' -v\n"""\nimport unittest\nfrom repairdesk.scenarios import replay\n\n\nclass ExportedRegression(unittest.TestCase):\n    def test_${s.id.replaceAll('-', '_')}(self):\n        result = replay(${JSON.stringify(s.id)})\n        self.assertEqual(result["outcome"]["status"], ${JSON.stringify(s.outcome.status)})\n        self.assertEqual(result["bronze"]["sha256"], ${JSON.stringify(s.bronze.sha256)})\n        self.assertEqual(result["metrics"]["repairs"], ${s.metrics.repairs})\n        for check in result["regression"]["checks"]:\n            with self.subTest(check=check["name"]):\n                self.assertTrue(check["passed"], check["detail"])\n\n\nif __name__ == "__main__":\n    unittest.main()\n`; }
  $('case-list').addEventListener('click', event => { const button = event.target.closest('[data-case]'); if (!button || state.busy) return; state.id = button.dataset.case; state.stage = 'bronze'; renderCases(); renderCase(); $('case-list').querySelector(`[data-case="${state.id}"]`).focus({ preventScroll: true }); });
  $('case-content').addEventListener('click', event => { const stage = event.target.closest('[data-stage]'); if (stage) { state.stage = stage.dataset.stage; renderCase(); $(`tab-${state.stage}`).focus({ preventScroll: true }); return; } const action = event.target.closest('[data-action]')?.dataset.action; const s = current(); if (action === 'replay') runReplay(); if (action === 'bundle') download(`repair-desk-${s.id}.json`, { meta: data.meta, evidence_mode: state.results.has(s.id) ? 'local-python-execution' : 'bundled-python-output', scenario: s }); if (action === 'test') download(`test_${s.id.replaceAll('-', '_')}.py`, regressionFile(s), 'text/x-python'); if (action === 'reply') download(`reply-${s.id}.txt`, `Illustrative support reply — The Repair Desk\nCase: ${s.ticket.subject}\n\n${s.support_reply}\n\nFictional ticket; no message has been sent.\n`, 'text/plain'); });
  $('case-content').addEventListener('keydown', event => { if (!event.target.matches('[role="tab"]') || !['ArrowRight', 'ArrowLeft', 'Home', 'End'].includes(event.key)) return; event.preventDefault(); const stages = ['bronze', 'silver', 'gold']; const i = stages.indexOf(state.stage); state.stage = event.key === 'Home' ? stages[0] : event.key === 'End' ? stages[2] : stages[(i + (event.key === 'ArrowRight' ? 1 : -1) + 3) % 3]; renderCase(); $(`tab-${state.stage}`).focus(); });
  $('evaluation-button').setAttribute('aria-expanded', 'false'); $('evaluation-button').setAttribute('aria-controls', 'evaluation-details'); $('evaluation-button').addEventListener('click', () => { const show = $('evaluation-details').hidden; $('evaluation-details').hidden = !show; $('evaluation-button').setAttribute('aria-expanded', String(show)); $('evaluation-button').innerHTML = `${show ? 'Close the test results' : 'Inspect the test results'} <span aria-hidden="true">${show ? '−' : '↗'}</span>`; });
  renderCases(); renderCase(); renderEvaluation(); renderSources();
  if (/^(127\.0\.0\.1|localhost|\[::1\])$/.test(location.hostname)) { fetch('/api/scenarios', { signal: AbortSignal.timeout(3000) }).then(r => r.ok ? r.json() : Promise.reject()).then(result => { if (result?.meta?.name !== data.meta.name || !Array.isArray(result.scenarios)) return; state.live = true; updateMode(); renderCase(); }).catch(() => {}); }
})();
